### PR TITLE
displayBuffer has been deprecated

### LINKED ISSUE #42: TextEditor.get is deprecated.
Atom 1.13.0-beta2 Deprecation Cop says:

`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.get (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:101:14)
toggleQuoteAtPosition (/home/duncan/.atom/packages/toggle-quotes/lib/toggle-quotes.js:31:21)
<unknown> (/home/duncan/.atom/packages/toggle-quotes/lib/toggle-quotes.js:13:7)
TextBuffer.transact (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:867:18)
TextEditor.transact (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:1566:26)
toggleQuotes (/home/duncan/.atom/packages/toggle-quotes/lib/toggle-quotes.js:10:10)
```

### PR DESCRIPTION
**Pull request by benphelps**
`TextEditor` now implements `bufferRangeForScopeAtPosition`.

Fixes #42

### CODE REVIEW

**Comment by benphelps** [comment]
This also fixes #39

**Comment by dsandstrom** [comment]
@50Wliu @lee-dohm Can we get some PR love?

**Comment by 50Wliu** [comment]
Looks fine to me.

**Comment by dsandstrom** [comment]
Muchas gracias mi amigos

**Pull request merged**
